apiVersion: v1
kind: Service
metadata:
  name: iot-poc-01-fs-srv
  labels:
    app: iot-poc-01
    tech: nodejs
    role: fullstack-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: iot-poc-01
    tech: nodejs
    role: fullstack
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: iot-poc-01-fs
  labels:
    app: iot-poc-01
    tech: nodejs
    role: fullstack
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: iot-poc-01
        tech: nodejs
        role: fullstack
    spec:
      containers:
      - name: master
        image: gcr.io/luca-paganelli-formazione/iot-poc-01-fs:0.0.2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
